import unittest
import DaijiJa

class DaijiJaTestCase(unittest.TestCase):
    def test_1degit(self):
        self.assertEqual(DaijiJa.daiji(0),'零')
        self.assertEqual(DaijiJa.daiji(1),'壱')
        self.assertEqual(DaijiJa.daiji(2),'弐')
        self.assertEqual(DaijiJa.daiji(3),'参')
        self.assertEqual(DaijiJa.daiji(4),'四')
        self.assertEqual(DaijiJa.daiji(5),'五')
        self.assertEqual(DaijiJa.daiji(6),'六')
        self.assertEqual(DaijiJa.daiji(7),'七')
        self.assertEqual(DaijiJa.daiji(8),'八')
        self.assertEqual(DaijiJa.daiji(9),'九')

    def test_1degit2(self):
        self.assertEqual(DaijiJa.daiji(0,mode=2),'零')
        self.assertEqual(DaijiJa.daiji(1,mode=2),'壹')
        self.assertEqual(DaijiJa.daiji(2,mode=2),'貳')
        self.assertEqual(DaijiJa.daiji(3,mode=2),'參')
        self.assertEqual(DaijiJa.daiji(4,mode=2),'四')
        self.assertEqual(DaijiJa.daiji(5,mode=2),'五')
        self.assertEqual(DaijiJa.daiji(6,mode=2),'六')
        self.assertEqual(DaijiJa.daiji(7,mode=2),'七')
        self.assertEqual(DaijiJa.daiji(8,mode=2),'八')
        self.assertEqual(DaijiJa.daiji(9,mode=2),'九')

    def test_1degit3(self):
        self.assertEqual(DaijiJa.daiji(0,mode=3),'零')
        self.assertEqual(DaijiJa.daiji(1,mode=3),'壹')
        self.assertEqual(DaijiJa.daiji(2,mode=3),'貳')
        self.assertEqual(DaijiJa.daiji(3,mode=3),'參')
        self.assertEqual(DaijiJa.daiji(4,mode=3),'肆')
        self.assertEqual(DaijiJa.daiji(5,mode=3),'伍')
        self.assertEqual(DaijiJa.daiji(6,mode=3),'陸')
        self.assertEqual(DaijiJa.daiji(7,mode=3),'漆')
        self.assertEqual(DaijiJa.daiji(8,mode=3),'捌')
        self.assertEqual(DaijiJa.daiji(9,mode=3),'玖')
    
    def test_2digit(self):
        self.assertEqual(DaijiJa.daiji(10),'壱拾')
        self.assertEqual(DaijiJa.daiji(11),'壱拾壱')
        self.assertEqual(DaijiJa.daiji(12),'壱拾弐')
        self.assertEqual(DaijiJa.daiji(13),'壱拾参')
        self.assertEqual(DaijiJa.daiji(14),'壱拾四')
        self.assertEqual(DaijiJa.daiji(15),'壱拾五')
        self.assertEqual(DaijiJa.daiji(16),'壱拾六')
        self.assertEqual(DaijiJa.daiji(17),'壱拾七')
        self.assertEqual(DaijiJa.daiji(18),'壱拾八')
        self.assertEqual(DaijiJa.daiji(19),'壱拾九')
        self.assertEqual(DaijiJa.daiji(20),'弐拾')
        self.assertEqual(DaijiJa.daiji(30),'参拾')
        self.assertEqual(DaijiJa.daiji(40),'四拾')
        self.assertEqual(DaijiJa.daiji(50),'五拾')
        self.assertEqual(DaijiJa.daiji(60),'六拾')
        self.assertEqual(DaijiJa.daiji(70),'七拾')
        self.assertEqual(DaijiJa.daiji(80),'八拾')
        self.assertEqual(DaijiJa.daiji(90),'九拾')
    
    def test_2digit2(self):
        self.assertEqual(DaijiJa.daiji(10,mode=2),'壹拾')
        self.assertEqual(DaijiJa.daiji(11,mode=2),'壹拾壹')
        self.assertEqual(DaijiJa.daiji(12,mode=2),'壹拾貳')
        self.assertEqual(DaijiJa.daiji(13,mode=2),'壹拾參')
        self.assertEqual(DaijiJa.daiji(14,mode=2),'壹拾四')
        self.assertEqual(DaijiJa.daiji(15,mode=2),'壹拾五')
        self.assertEqual(DaijiJa.daiji(16,mode=2),'壹拾六')
        self.assertEqual(DaijiJa.daiji(17,mode=2),'壹拾七')
        self.assertEqual(DaijiJa.daiji(18,mode=2),'壹拾八')
        self.assertEqual(DaijiJa.daiji(19,mode=2),'壹拾九')
        self.assertEqual(DaijiJa.daiji(20,mode=2),'貳拾')
        self.assertEqual(DaijiJa.daiji(30,mode=2),'參拾')
        self.assertEqual(DaijiJa.daiji(40,mode=2),'四拾')
        self.assertEqual(DaijiJa.daiji(50,mode=2),'五拾')
        self.assertEqual(DaijiJa.daiji(60,mode=2),'六拾')
        self.assertEqual(DaijiJa.daiji(70,mode=2),'七拾')
        self.assertEqual(DaijiJa.daiji(80,mode=2),'八拾')
        self.assertEqual(DaijiJa.daiji(90,mode=2),'九拾')

    def test_2digit3(self):
        self.assertEqual(DaijiJa.daiji(10,mode=3),'壹拾')
        self.assertEqual(DaijiJa.daiji(11,mode=3),'壹拾壹')
        self.assertEqual(DaijiJa.daiji(12,mode=3),'壹拾貳')
        self.assertEqual(DaijiJa.daiji(13,mode=3),'壹拾參')
        self.assertEqual(DaijiJa.daiji(14,mode=3),'壹拾肆')
        self.assertEqual(DaijiJa.daiji(15,mode=3),'壹拾伍')
        self.assertEqual(DaijiJa.daiji(16,mode=3),'壹拾陸')
        self.assertEqual(DaijiJa.daiji(17,mode=3),'壹拾漆')
        self.assertEqual(DaijiJa.daiji(18,mode=3),'壹拾捌')
        self.assertEqual(DaijiJa.daiji(19,mode=3),'壹拾玖')
        self.assertEqual(DaijiJa.daiji(20,mode=3),'貳拾')
        self.assertEqual(DaijiJa.daiji(30,mode=3),'參拾')
        self.assertEqual(DaijiJa.daiji(40,mode=3),'肆拾')
        self.assertEqual(DaijiJa.daiji(50,mode=3),'伍拾')
        self.assertEqual(DaijiJa.daiji(60,mode=3),'陸拾')
        self.assertEqual(DaijiJa.daiji(70,mode=3),'漆拾')
        self.assertEqual(DaijiJa.daiji(80,mode=3),'捌拾')
        self.assertEqual(DaijiJa.daiji(90,mode=3),'玖拾')

    def test_3digit(self):
        self.assertEqual(DaijiJa.daiji(100),'壱百')
        self.assertEqual(DaijiJa.daiji(101),'壱百壱')
        self.assertEqual(DaijiJa.daiji(123),'壱百弐拾参')
        self.assertEqual(DaijiJa.daiji(200),'弐百')
        self.assertEqual(DaijiJa.daiji(300),'参百')
        self.assertEqual(DaijiJa.daiji(400),'四百')
        self.assertEqual(DaijiJa.daiji(500),'五百')
        self.assertEqual(DaijiJa.daiji(600),'六百')
        self.assertEqual(DaijiJa.daiji(700),'七百')
        self.assertEqual(DaijiJa.daiji(800),'八百')
        self.assertEqual(DaijiJa.daiji(900),'九百')
    
    def test_3digit2(self):
        self.assertEqual(DaijiJa.daiji(100,mode=2),'壹百')
        self.assertEqual(DaijiJa.daiji(101,mode=2),'壹百壹')
        self.assertEqual(DaijiJa.daiji(123,mode=2),'壹百貳拾參')
        self.assertEqual(DaijiJa.daiji(200,mode=2),'貳百')
        self.assertEqual(DaijiJa.daiji(300,mode=2),'參百')
        self.assertEqual(DaijiJa.daiji(400,mode=2),'四百')
        self.assertEqual(DaijiJa.daiji(500,mode=2),'五百')
        self.assertEqual(DaijiJa.daiji(600,mode=2),'六百')
        self.assertEqual(DaijiJa.daiji(700,mode=2),'七百')
        self.assertEqual(DaijiJa.daiji(800,mode=2),'八百')
        self.assertEqual(DaijiJa.daiji(900,mode=2),'九百')

    def test_3digit3(self):
        self.assertEqual(DaijiJa.daiji(100,mode=3),'壹佰')
        self.assertEqual(DaijiJa.daiji(101,mode=3),'壹佰壹')
        self.assertEqual(DaijiJa.daiji(123,mode=3),'壹佰貳拾參')
        self.assertEqual(DaijiJa.daiji(200,mode=3),'貳佰')
        self.assertEqual(DaijiJa.daiji(300,mode=3),'參佰')
        self.assertEqual(DaijiJa.daiji(400,mode=3),'肆佰')
        self.assertEqual(DaijiJa.daiji(500,mode=3),'伍佰')
        self.assertEqual(DaijiJa.daiji(600,mode=3),'陸佰')
        self.assertEqual(DaijiJa.daiji(700,mode=3),'漆佰')
        self.assertEqual(DaijiJa.daiji(800,mode=3),'捌佰')
        self.assertEqual(DaijiJa.daiji(900,mode=3),'玖佰')

    def test_4digit(self):
        self.assertEqual(DaijiJa.daiji(1000),'壱千')
        self.assertEqual(DaijiJa.daiji(1001),'壱千壱')
        self.assertEqual(DaijiJa.daiji(1010),'壱千壱拾')
        self.assertEqual(DaijiJa.daiji(1011),'壱千壱拾壱')
        self.assertEqual(DaijiJa.daiji(1100),'壱千壱百')
        self.assertEqual(DaijiJa.daiji(1101),'壱千壱百壱')
        self.assertEqual(DaijiJa.daiji(1110),'壱千壱百壱拾')
        self.assertEqual(DaijiJa.daiji(1111),'壱千壱百壱拾壱')
        self.assertEqual(DaijiJa.daiji(2000),'弐千')
        self.assertEqual(DaijiJa.daiji(3000),'参千')
        self.assertEqual(DaijiJa.daiji(4000),'四千')
        self.assertEqual(DaijiJa.daiji(5000),'五千')
        self.assertEqual(DaijiJa.daiji(6000),'六千')
        self.assertEqual(DaijiJa.daiji(7000),'七千')
        self.assertEqual(DaijiJa.daiji(8000),'八千')
        self.assertEqual(DaijiJa.daiji(9000),'九千')
    
    def test_4digit2(self):
        self.assertEqual(DaijiJa.daiji(1000,mode=2),'壹千')
        self.assertEqual(DaijiJa.daiji(1001,mode=2),'壹千壹')
        self.assertEqual(DaijiJa.daiji(1010,mode=2),'壹千壹拾')
        self.assertEqual(DaijiJa.daiji(1011,mode=2),'壹千壹拾壹')
        self.assertEqual(DaijiJa.daiji(1100,mode=2),'壹千壹百')
        self.assertEqual(DaijiJa.daiji(1101,mode=2),'壹千壹百壹')
        self.assertEqual(DaijiJa.daiji(1110,mode=2),'壹千壹百壹拾')
        self.assertEqual(DaijiJa.daiji(1111,mode=2),'壹千壹百壹拾壹')
        self.assertEqual(DaijiJa.daiji(2000,mode=2),'貳千')
        self.assertEqual(DaijiJa.daiji(3000,mode=2),'參千')
        self.assertEqual(DaijiJa.daiji(4000,mode=2),'四千')
        self.assertEqual(DaijiJa.daiji(5000,mode=2),'五千')
        self.assertEqual(DaijiJa.daiji(6000,mode=2),'六千')
        self.assertEqual(DaijiJa.daiji(7000,mode=2),'七千')
        self.assertEqual(DaijiJa.daiji(8000,mode=2),'八千')
        self.assertEqual(DaijiJa.daiji(9000,mode=2),'九千')

    def test_4digit3(self):
        self.assertEqual(DaijiJa.daiji(1000,mode=3),'壹仟')
        self.assertEqual(DaijiJa.daiji(1001,mode=3),'壹仟壹')
        self.assertEqual(DaijiJa.daiji(1010,mode=3),'壹仟壹拾')
        self.assertEqual(DaijiJa.daiji(1011,mode=3),'壹仟壹拾壹')
        self.assertEqual(DaijiJa.daiji(1100,mode=3),'壹仟壹佰')
        self.assertEqual(DaijiJa.daiji(1101,mode=3),'壹仟壹佰壹')
        self.assertEqual(DaijiJa.daiji(1110,mode=3),'壹仟壹佰壹拾')
        self.assertEqual(DaijiJa.daiji(1111,mode=3),'壹仟壹佰壹拾壹')
        self.assertEqual(DaijiJa.daiji(2000,mode=3),'貳仟')
        self.assertEqual(DaijiJa.daiji(3000,mode=3),'參仟')
        self.assertEqual(DaijiJa.daiji(4000,mode=3),'肆仟')
        self.assertEqual(DaijiJa.daiji(5000,mode=3),'伍仟')
        self.assertEqual(DaijiJa.daiji(6000,mode=3),'陸仟')
        self.assertEqual(DaijiJa.daiji(7000,mode=3),'漆仟')
        self.assertEqual(DaijiJa.daiji(8000,mode=3),'捌仟')
        self.assertEqual(DaijiJa.daiji(9000,mode=3),'玖仟')

    def test_5digit(self):
        self.assertEqual(DaijiJa.daiji(10000),'壱万')
        self.assertEqual(DaijiJa.daiji(10001),'壱万壱')
        self.assertEqual(DaijiJa.daiji(100000),'壱拾万')
        self.assertEqual(DaijiJa.daiji(100010),'壱拾万壱拾')
        self.assertEqual(DaijiJa.daiji(101100),'壱拾万壱千壱百')
        self.assertEqual(DaijiJa.daiji(1000000),'壱百万')
        self.assertEqual(DaijiJa.daiji(1001000),'壱百万壱千')
        self.assertEqual(DaijiJa.daiji(10000000),'壱千万')
        self.assertEqual(DaijiJa.daiji(10000100),'壱千万壱百')
        self.assertEqual(DaijiJa.daiji(20000),'弐万')
        self.assertEqual(DaijiJa.daiji(30000),'参万')
        self.assertEqual(DaijiJa.daiji(40000),'四万')
        self.assertEqual(DaijiJa.daiji(50000),'五万')
        self.assertEqual(DaijiJa.daiji(60000),'六万')
        self.assertEqual(DaijiJa.daiji(70000),'七万')
        self.assertEqual(DaijiJa.daiji(80000),'八万')
        self.assertEqual(DaijiJa.daiji(90000),'九万')
    
    def test_5digit2(self):
        self.assertEqual(DaijiJa.daiji(10000,mode=2),'壹万')
        self.assertEqual(DaijiJa.daiji(10001,mode=2),'壹万壹')
        self.assertEqual(DaijiJa.daiji(100000,mode=2),'壹拾万')
        self.assertEqual(DaijiJa.daiji(100010,mode=2),'壹拾万壹拾')
        self.assertEqual(DaijiJa.daiji(101100,mode=2),'壹拾万壹千壹百')
        self.assertEqual(DaijiJa.daiji(1000000,mode=2),'壹百万')
        self.assertEqual(DaijiJa.daiji(1001000,mode=2),'壹百万壹千')
        self.assertEqual(DaijiJa.daiji(10000000,mode=2),'壹千万')
        self.assertEqual(DaijiJa.daiji(10000100,mode=2),'壹千万壹百')
        self.assertEqual(DaijiJa.daiji(20000,mode=2),'貳万')
        self.assertEqual(DaijiJa.daiji(30000,mode=2),'參万')
        self.assertEqual(DaijiJa.daiji(40000,mode=2),'四万')
        self.assertEqual(DaijiJa.daiji(50000,mode=2),'五万')
        self.assertEqual(DaijiJa.daiji(60000,mode=2),'六万')
        self.assertEqual(DaijiJa.daiji(70000,mode=2),'七万')
        self.assertEqual(DaijiJa.daiji(80000,mode=2),'八万')
        self.assertEqual(DaijiJa.daiji(90000,mode=2),'九万')

    def test_5digit3(self):
        self.assertEqual(DaijiJa.daiji(10000,mode=3),'壹萬')
        self.assertEqual(DaijiJa.daiji(10001,mode=3),'壹萬壹')
        self.assertEqual(DaijiJa.daiji(100000,mode=3),'壹拾萬')
        self.assertEqual(DaijiJa.daiji(100010,mode=3),'壹拾萬壹拾')
        self.assertEqual(DaijiJa.daiji(101100,mode=3),'壹拾萬壹仟壹佰')
        self.assertEqual(DaijiJa.daiji(1000000,mode=3),'壹佰萬')
        self.assertEqual(DaijiJa.daiji(1001000,mode=3),'壹佰萬壹仟')
        self.assertEqual(DaijiJa.daiji(10000000,mode=3),'壹仟萬')
        self.assertEqual(DaijiJa.daiji(10000100,mode=3),'壹仟萬壹佰')
        self.assertEqual(DaijiJa.daiji(20000,mode=3),'貳萬')
        self.assertEqual(DaijiJa.daiji(30000,mode=3),'參萬')
        self.assertEqual(DaijiJa.daiji(40000,mode=3),'肆萬')
        self.assertEqual(DaijiJa.daiji(50000,mode=3),'伍萬')
        self.assertEqual(DaijiJa.daiji(60000,mode=3),'陸萬')
        self.assertEqual(DaijiJa.daiji(70000,mode=3),'漆萬')
        self.assertEqual(DaijiJa.daiji(80000,mode=3),'捌萬')
        self.assertEqual(DaijiJa.daiji(90000,mode=3),'玖萬')

    def test_9digit(self):
        self.assertEqual(DaijiJa.daiji(100000000),'壱億')
        self.assertEqual(DaijiJa.daiji(100010000),'壱億壱万')
        self.assertEqual(DaijiJa.daiji(100010001),'壱億壱万壱')
        self.assertEqual(DaijiJa.daiji(1000000000),'壱拾億')
        self.assertEqual(DaijiJa.daiji(10000000000),'壱百億')
        self.assertEqual(DaijiJa.daiji(100000000000),'壱千億')
        self.assertEqual(DaijiJa.daiji(200000000),'弐億')
        self.assertEqual(DaijiJa.daiji(300000000),'参億')
        self.assertEqual(DaijiJa.daiji(400000000),'四億')
        self.assertEqual(DaijiJa.daiji(500000000),'五億')
        self.assertEqual(DaijiJa.daiji(600000000),'六億')
        self.assertEqual(DaijiJa.daiji(700000000),'七億')
        self.assertEqual(DaijiJa.daiji(800000000),'八億')
        self.assertEqual(DaijiJa.daiji(900000000),'九億')
    
    def test_9digit2(self):
        self.assertEqual(DaijiJa.daiji(100000000,mode=2),'壹億')
        self.assertEqual(DaijiJa.daiji(100010000,mode=2),'壹億壹万')
        self.assertEqual(DaijiJa.daiji(100010001,mode=2),'壹億壹万壹')
        self.assertEqual(DaijiJa.daiji(1000000000,mode=2),'壹拾億')
        self.assertEqual(DaijiJa.daiji(10000000000,mode=2),'壹百億')
        self.assertEqual(DaijiJa.daiji(100000000000,mode=2),'壹千億')
        self.assertEqual(DaijiJa.daiji(200000000,mode=2),'貳億')
        self.assertEqual(DaijiJa.daiji(300000000,mode=2),'參億')
        self.assertEqual(DaijiJa.daiji(400000000,mode=2),'四億')
        self.assertEqual(DaijiJa.daiji(500000000,mode=2),'五億')
        self.assertEqual(DaijiJa.daiji(600000000,mode=2),'六億')
        self.assertEqual(DaijiJa.daiji(700000000,mode=2),'七億')
        self.assertEqual(DaijiJa.daiji(800000000,mode=2),'八億')
        self.assertEqual(DaijiJa.daiji(900000000,mode=2),'九億')

    def test_9digit3(self):
        self.assertEqual(DaijiJa.daiji(100000000,mode=3),'壹億')
        self.assertEqual(DaijiJa.daiji(100010000,mode=3),'壹億壹萬')
        self.assertEqual(DaijiJa.daiji(100010001,mode=3),'壹億壹萬壹')
        self.assertEqual(DaijiJa.daiji(1000000000,mode=3),'壹拾億')
        self.assertEqual(DaijiJa.daiji(10000000000,mode=3),'壹佰億')
        self.assertEqual(DaijiJa.daiji(100000000000,mode=3),'壹仟億')
        self.assertEqual(DaijiJa.daiji(200000000,mode=3),'貳億')
        self.assertEqual(DaijiJa.daiji(300000000,mode=3),'參億')
        self.assertEqual(DaijiJa.daiji(400000000,mode=3),'肆億')
        self.assertEqual(DaijiJa.daiji(500000000,mode=3),'伍億')
        self.assertEqual(DaijiJa.daiji(600000000,mode=3),'陸億')
        self.assertEqual(DaijiJa.daiji(700000000,mode=3),'漆億')
        self.assertEqual(DaijiJa.daiji(800000000,mode=3),'捌億')
        self.assertEqual(DaijiJa.daiji(900000000,mode=3),'玖億')

    def test_limit(self):
        # Testing Boundaries
        self.assertEqual(DaijiJa.daiji(0),'零')
        with self.assertRaises(ValueError):
            DaijiJa.daiji(-1)
        self.assertEqual(DaijiJa.daiji(999999999999),'九千九百九拾九億九千九百九拾九万九千九百九拾九')
        with self.assertRaises(ValueError):
            DaijiJa.daiji(1000000000000)

        # Testing non natural numbers
        with self.assertRaises(TypeError):
            DaijiJa.daiji('abc')
        with self.assertRaises(TypeError):
            DaijiJa.daiji(1.0)